[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$OutDir,[Parameter(Mandatory=$true)][long]$EvaluatedAt,[string]$RepoRoot=(Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),[string]$CodeIntel=(Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) "target\debug\code-intel.exe"))
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop";if($EvaluatedAt-le0){throw "bad time"};if(Test-Path $OutDir){throw "exclusive output required"};if(-not(Test-Path $CodeIntel -PathType Leaf)){throw "binary missing"};New-Item -ItemType Directory $OutDir|Out-Null;New-Item -ItemType Directory (Join-Path $OutDir evidence)|Out-Null
function W([string]$p,[object]$v){[IO.File]::WriteAllText($p,($v|ConvertTo-Json -Depth 30 -Compress),[Text.UTF8Encoding]::new($false))};function S([string]$t){([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($t)))).ToLowerInvariant()};function Ref([string]$s,[string]$t,[string]$r){$p=Join-Path $OutDir ($r-replace'/',[IO.Path]::DirectorySeparatorChar);[ordered]@{schema="code-intel-artifact-ref.v1";artifactSchema=$s;type=$t;path=($r-replace'\\','/');sha256=((Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant());consumedSnapshotIdentity=$snapshot}}
$tests=@('provider_quota_precedes_missing_current_graph_and_is_replay_stable','precedence_matrix_matches_the_legacy_stable_diagnoses_and_fails_closed','missing_or_non_admitted_authority_is_rejected_and_enrichment_never_overrides_it','conflicting_or_provider_injected_modalities_fail_closed_independent_of_input_order','markdown_is_a_rebuildable_view_and_cannot_change_the_machine_verdict','a09_seeded_path_executes_hospital_through_a01_and_rejects_snapshot_mismatch','legacy_facade_and_rust_execute_the_same_fixture_with_stable_machine_parity');foreach($n in $tests){& cargo test -q -p code-intel --test hospital_diagnosis $n -- --exact|Out-Null;if($LASTEXITCODE-ne0){throw "B09 test failed $n"}}
$boundary=& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "tools\compatibility\Test-HospitalRetirementBoundary.ps1")|ConvertFrom-Json;$runPath=Join-Path $RepoRoot "run-code-intel.ps1";$run=[IO.File]::ReadAllText($runPath);$base=$run.Replace("`r`n","`n").Replace("`r","`n")
$functions='(?s)function New-HospitalProtocol \{.*?(?=\nfunction Get-CodeIntelSentruxStep)';$call='(?s)\$hospitalReport = New-CodeIntelHospitalReport .*?Convert-HospitalReportToMarkdown \$hospitalReport \| Set-Content -LiteralPath \$hospitalMarkdownPath -Encoding UTF8\n';$matches=@([regex]::Match($base,$functions),[regex]::Match($base,$call))|Sort-Object Index;if($matches.Where({-not$_.Success}).Count){throw "bounded E08 branch absent"}
$frozen=@('run-code-intel.ps1','crates/code-intel-cli/src/hospital_diagnosis.rs','orchestration/integrations.json','crates/code-intel-cli/src/run_commit.rs','crates/code-intel-cli/src/artifact_index.rs','crates/code-intel-cli/src/doctor_adapter.rs');$digests=@{};foreach($p in $frozen){$digests[$p]=(Get-FileHash (Join-Path $RepoRoot $p) -Algorithm SHA256).Hash.ToLowerInvariant()};$snapshot=S (($frozen|ForEach-Object{$digests[$_]})-join"`n")
$rid="retire-hospital-branch";$bid="run-code-intel.hospital.embedded-diagnosis-render";$rep="diagnosis.hospital";$callPath="run-code-intel.ps1::$bid";$expiry=$EvaluatedAt+2592000
function E([string]$n,[string]$c,[object]$d){$v=[ordered]@{schema="code-intel-compatibility-retirement-evidence.v1";snapshotIdentity=$snapshot;id="e08.$n";evidenceClass=$c;retirementId=$rid;legacyBranchId=$bid;replacementCapabilityId=$rep;details=$d};$r="evidence/$n.json";W (Join-Path $OutDir $r) $v;Ref "code-intel-compatibility-retirement-evidence.v1" "compatibility.retirement-evidence" $r}
$atom=E "replacement-atom" "replacement_atom" ([ordered]@{outcome="blocked";status="pending_facade_route";capability=$rep;b09RegistryAvailable=$true;normalFacadeUsesB09=$boundary.normalFacadeUsesB09;blocker="normal facade still executes embedded Hospital authority"})
$gold=E "golden-parity" "golden_parity" ([ordered]@{outcome="passed";assertionCount=3;executedTestCount=$tests.Count;sameUntrustedAuthoritativeFixture=$true;machineParity=$true;testFunctions=$tests})
$contract=E "contract-parity" "contract_parity" ([ordered]@{outcome="passed";assertionCount=7;precedenceFailClosed=$true;a09SeededA01Route=$true;authoritativeEvidenceCannotBeOverridden=$true})
$effects=E "effect-parity" "effect_parity" ([ordered]@{outcome="passed";assertionCount=4;declaredEffects=@("local_write");machineAuthority="hospital-report.json";markdownRebuildable=$true;untrustedViewCannotChangeVerdict=$true})
$registry=E "registry-reconciliation" "registry_reconciliation" ([ordered]@{outcome="passed";registryParticipantId="diagnosis.hospital";replacementCapabilityId=$rep;status="declared";embeddedFunctionBlocks=1;embeddedCallBlocks=1;normalRouteStatus="legacy_authority"})
$window=E "compatibility-window" "compatibility_window" ([ordered]@{outcome="blocked";startedAt=$EvaluatedAt;observedThrough=$EvaluatedAt;minimumDays=30;checkedAt=$EvaluatedAt;expiresAt=$expiry;blocker="no completed 30-day B09 normal-route observation"})
$rr="work/e08-hospital-rollback-$EvaluatedAt";$rc="pwsh -NoLogo -NoProfile -File tools/compatibility/Restore-HospitalLegacyBranch.ps1 -RehearsalRoot $rr";$rollbackResult=& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "tools\compatibility\Restore-HospitalLegacyBranch.ps1") -RehearsalRoot (Join-Path $RepoRoot ($rr-replace'/',[IO.Path]::DirectorySeparatorChar))|ConvertFrom-Json;if($LASTEXITCODE-ne0-or$rollbackResult.exactRestore-ne$true){throw "rollback failed"}
$rollback=E "rollback-execution" "rollback_execution" ([ordered]@{outcome="passed";command=$rc;executedAt=$EvaluatedAt;exitCode=0;target="$rr/run-code-intel.ps1";exactRestore=$rollbackResult.exactRestore;sourceSha256=$rollbackResult.sourceSha256;targetSha256=$rollbackResult.targetSha256;replacementChanged=$false;publicationChanged=$false;indexChanged=$false;doctorChanged=$false})
$usage=E "usage-observation" "usage_observation" ([ordered]@{outcome="blocked";startedAt=$EvaluatedAt;endedAt=$EvaluatedAt;totalInvocations=0;legacyInvocations=0;replacementInvocations=0;blocker="no production usage observation"})
$trace='{"legacyBranchId":"'+$bid+'","replacementCapabilityId":"'+$rep+'","retirementId":"'+$rid+'"}';$necessity=E "c00-necessity" "c00_necessity" ([ordered]@{outcome="passed";decision="admit";changeId=$rid;necessityTraceSha256=(S $trace)})
$b07=E "dependency-b07" "dependency_approval" ([ordered]@{outcome="passed";dependencyId="integration.registry-reconcile";status="approved";reviewer="e08-author"});$a04=E "dependency-a04" "dependency_approval" ([ordered]@{outcome="passed";dependencyId="evidence.admissibility";status="approved";reviewer="e08-author"})
$subject=[ordered]@{legacyBranch=[ordered]@{capabilityId="diagnosis.hospital.legacy-powershell";branchId=$bid;callPath=$callPath;affectedFiles=@("run-code-intel.ps1");owner="executor-hospital";registryParticipantId="diagnosis.hospital"};replacement=[ordered]@{capabilityId=$rep;implementationId="diagnosis.hospital.compat";dependencies=@("integration.registry-reconcile","evidence.admissibility");atomEvidence=$atom};parity=[ordered]@{golden=$gold;contract=$contract;effects=$effects};registryReconciliation=$registry;compatibilityWindow=$window;rollback=[ordered]@{command=$rc;executionEvidence=$rollback};usageObservation=$usage;necessityEvidence=$necessity;dependencyStates=@($b07,$a04);lineReductionEvidence=$false}
$independent=E "independent-approval" "independent_approval" ([ordered]@{outcome="blocked";approved=$false;authorIndependent=$false;subjectSha256=("0"*64);reviewer="independent-verifier-required";authorityEvent=[ordered]@{};blocker="no independent approval"});$manifest=[ordered]@{schema="code-intel-compatibility-retirement-manifest.v1";snapshotIdentity=$snapshot;retirementId=$rid;approvalSubject=$subject;independentApproval=$independent};W (Join-Path $OutDir "compatibility-retirement-manifest.json") $manifest;$manifestRef=Ref "code-intel-compatibility-retirement-manifest.v1" "compatibility.retirement-manifest" "compatibility-retirement-manifest.json"
$registryJson=Get-Content (Join-Path $RepoRoot "orchestration\integrations.json") -Raw|ConvertFrom-Json;$gateDecl=($registryJson.integrations|Where-Object id -eq "compatibility.retirement-gate").capabilityDeclaration
$gate=[ordered]@{schema="code-intel-capability-request.v1";capability="compatibility.retirement-gate";contractVersion=1;implementation=$gateDecl.implementation;snapshot=[ordered]@{identity=$snapshot;repoIdentity=("content-v1:"+("c"*64));head="working-tree-e08";workingTreePolicy="explicit_overlay";scope=@(".");inputDigest=("d"*64)};options=[ordered]@{evaluatedAt=$EvaluatedAt};inputs=@($manifestRef,$atom,$gold,$contract,$effects,$registry,$window,$rollback,$usage,$necessity,$b07,$a04,$independent);effectPolicy=[ordered]@{allowedEffects=$gateDecl.allowedEffects}}
W (Join-Path $OutDir "e00-request.json") $gate;$gateOut=Join-Path $OutDir "gate-out";& $CodeIntel capability exec compatibility.retirement-gate --request (Join-Path $OutDir "e00-request.json") --out $gateOut --artifact-root $OutDir|Out-Null;if($LASTEXITCODE-ne0){throw "E00 failed"};$decision=Get-Content (Join-Path $gateOut "compatibility-retirement-decision.json") -Raw|ConvertFrom-Json;if($decision.decision-ne"blocked"){throw "E08 must remain blocked"}
$deleted=0;$hunks=@($matches|ForEach-Object{$value=$_.Value;$lines=@($value-split"`n");$old=@($base.Substring(0,$_.Index)-split"`n").Count;$h=[ordered]@{addedLines=@();deletedLines=$lines;newLines=0;newStart=$old-$deleted;oldLines=$lines.Count;oldStart=$old};$deleted+=$lines.Count;$h})
$baseLines=@($base-split"`n");$resultLines=for($i=1;$i-le$baseLines.Count;$i++){if(-not@($hunks|Where-Object{$i-ge$_.oldStart-and$i-lt($_.oldStart+$_.oldLines)}).Count){$baseLines[$i-1]}};$result=$resultLines-join"`n"
$files=@([ordered]@{baseBlobSha256=(S $base);baseText=$base;hunks=$hunks;path="run-code-intel.ps1";resultBlobSha256=(S $result);resultText=$result})
$diff=[ordered]@{schema="code-intel-compatibility-retirement-deletion-diff.v1";snapshotIdentity=$snapshot;retirementId=$rid;legacyBranchId=$bid;affectedFiles=@("run-code-intel.ps1");deletionsOnly=$true;summary="Two-hunk deletion is limited to embedded Hospital diagnosis/rendering functions and their invocation; B09 semantics, publication, index, and doctor paths are excluded.";patch=[ordered]@{algorithm="replayable-delete-only-v1";sha256=(S (ConvertTo-Json -InputObject $files -Depth 30 -Compress));files=$files}}
W (Join-Path $OutDir "compatibility-retirement-deletion-diff.json") $diff;$diffRef=Ref "code-intel-compatibility-retirement-deletion-diff.v1" "compatibility.retirement-deletion-diff" "compatibility-retirement-deletion-diff.json";$decisionRef=Ref "code-intel-compatibility-retirement-decision.v1" "compatibility.retirement-decision" "gate-out/compatibility-retirement-decision.json"
$ticket=[ordered]@{schema="code-intel-compatibility-retirement-ticket-template.v1";snapshotIdentity=$snapshot;ticketId="ticket-e08-retire-hospital-branch";retirementId=$rid;legacyBranch=[ordered]@{capabilityId="diagnosis.hospital.legacy-powershell";branchId=$bid;callPath=$callPath};replacement=[ordered]@{capabilityId=$rep;dependencies=@("integration.registry-reconcile","evidence.admissibility")};affectedFiles=@("run-code-intel.ps1");evidence=[ordered]@{golden=$gold;contract=$contract;effects=$effects;usage=$usage;rollbackRehearsal=$rollback;deletionDiff=$diffRef};source=[ordered]@{retirementDecision=$decisionRef;retirementManifest=$manifestRef};owner="executor-hospital";verifier="independent-verifier-required";observationExpiry=$expiry;status="draft";authorityBoundary="template_only_no_approval_or_deletion_authority"}
W (Join-Path $OutDir "compatibility-retirement-ticket.json") $ticket;& $CodeIntel compatibility retirement-ticket lint --ticket (Join-Path $OutDir "compatibility-retirement-ticket.json") --evaluated-at $EvaluatedAt|Out-Null;if($LASTEXITCODE-ne0){throw "E01 lint failed"};$ticketRef=Ref "code-intel-compatibility-retirement-ticket-template.v1" "compatibility.retirement-ticket-template" "compatibility-retirement-ticket.json";$ticketDecl=($registryJson.integrations|Where-Object id -eq "compatibility.retirement-ticket-template").capabilityDeclaration
$e01=[ordered]@{schema="code-intel-capability-request.v1";capability="compatibility.retirement-ticket-template";contractVersion=1;implementation=$ticketDecl.implementation;snapshot=$gate.snapshot;options=[ordered]@{evaluatedAt=$EvaluatedAt};inputs=@($ticketRef,$manifestRef,$decisionRef,$diffRef);effectPolicy=[ordered]@{allowedEffects=$ticketDecl.allowedEffects}};W (Join-Path $OutDir "e01-request.json") $e01
$o=@(& $CodeIntel capability exec compatibility.retirement-ticket-template --request (Join-Path $OutDir "e01-request.json") --out (Join-Path $OutDir "e01-out") --artifact-root $OutDir 2>&1);$x=$LASTEXITCODE;$txt=$o-join"`n";[IO.File]::WriteAllText((Join-Path $OutDir "e01-stderr.txt"),$txt,[Text.UTF8Encoding]::new($false));if($x-ne65-or$txt-notmatch"ticket requires an approved E00 decision"){throw "E01 must validate patch then reject blocked E00: $x $txt"}
foreach($p in $frozen){if((Get-FileHash (Join-Path $RepoRoot $p) -Algorithm SHA256).Hash.ToLowerInvariant()-ne$digests[$p]){throw "E08 changed frozen path: $p"}}
$status=[ordered]@{schema="code-intel-compatibility-retirement-execution-status.v1";retirementId=$rid;decision="blocked";deletionExecuted=$false;retired=$false;liveEmbeddedAuthority=$true;normalFacadeUsesB09=$false;blockers=@($decision.blockers);gainLedgerProjection=$decision.gainLedgerProjection;boundary="B09 is registered but the normal facade still executes embedded Hospital authority; E08 has no deletion authority and excludes publication, index, and doctor."};W (Join-Path $OutDir "status.json") $status;$status|ConvertTo-Json -Depth 10 -Compress
