[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$OutDir,[Parameter(Mandatory=$true)][long]$EvaluatedAt,[string]$RepoRoot=(Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),[string]$CodeIntel=(Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) "target\debug\code-intel.exe"))
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
if($EvaluatedAt-le0){throw "EvaluatedAt must be positive"};if(Test-Path $OutDir){throw "packet output must be exclusive"};if(-not(Test-Path $CodeIntel -PathType Leaf)){throw "binary missing"}
New-Item -ItemType Directory $OutDir|Out-Null;New-Item -ItemType Directory (Join-Path $OutDir evidence)|Out-Null
function Write-Json([string]$p,[object]$v){[IO.File]::WriteAllText($p,($v|ConvertTo-Json -Depth 30 -Compress),[Text.UTF8Encoding]::new($false))}
function ShaText([string]$t){([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($t)))).ToLowerInvariant()}
function Ref([string]$s,[string]$t,[string]$r){$p=Join-Path $OutDir ($r-replace'/',[IO.Path]::DirectorySeparatorChar);[ordered]@{schema="code-intel-artifact-ref.v1";artifactSchema=$s;type=$t;path=($r-replace'\\','/');sha256=((Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant());consumedSnapshotIdentity=$snapshot}}
$boundary=(& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "tools\compatibility\Test-PublicationRetirementBoundary.ps1")|ConvertFrom-Json)
& cargo test -p code-intel --test run_commit staged_run_is_promoted_and_completion_marker_is_published_last --quiet|Out-Null;if($LASTEXITCODE-ne0){throw "marker-last test failed"}
& cargo test -p code-intel --test run_commit every_publication_phase_is_fail_closed_and_post_promotion_is_recoverable --quiet|Out-Null;if($LASTEXITCODE-ne0){throw "A07 phase matrix failed"}
& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "scripts/tests/test-dag-facade.ps1")|Out-Null;if($LASTEXITCODE-ne0){throw "A09 facade parity failed"}
$runPath=Join-Path $RepoRoot "run-code-intel.ps1";$run=[IO.File]::ReadAllText($runPath);$indexPath=Join-Path $RepoRoot "update-code-intel-index.ps1";$indexHash=(Get-FileHash $indexPath -Algorithm SHA256).Hash.ToLowerInvariant()
$initial='(?s)\$stagingNonce = \[guid\]::NewGuid\(\)\.ToString\("N"\)\.Substring\(0, 12\).*?New-Item -ItemType Directory -Force -Path \$runDir \| Out-Null\r?\n'
$final='(?s)# A run is authoritative only after every materialized view has been written,.*?Set-Content -LiteralPath \(Join-Path \$runDir "run-complete\.json"\) -Encoding UTF8\r?\n'
$base=$run.Replace("`r`n","`n").Replace("`r","`n");$matches=@([regex]::Match($base,$initial),[regex]::Match($base,$final))|Sort-Object Index;if($matches.Where({-not$_.Success}).Count){throw "bounded E05 branch absent"}
$snapshot=ShaText (((Get-FileHash $runPath -Algorithm SHA256).Hash.ToLowerInvariant()+"`n"+$indexHash+"`n"+($matches.Value-join"`n")))
$rid="retire-publication-branch";$bid="run-code-intel.publication.legacy-staging-marker";$rep="run.commit";$call="run-code-intel.ps1::$bid";$expiry=$EvaluatedAt+2592000
function Ev([string]$n,[string]$c,[object]$d){$v=[ordered]@{schema="code-intel-compatibility-retirement-evidence.v1";snapshotIdentity=$snapshot;id="e05.$n";evidenceClass=$c;retirementId=$rid;legacyBranchId=$bid;replacementCapabilityId=$rep;details=$d};$r="evidence/$n.json";Write-Json (Join-Path $OutDir $r) $v;Ref "code-intel-compatibility-retirement-evidence.v1" "compatibility.retirement-evidence" $r}
$atom=Ev "replacement-atom" "replacement_atom" ([ordered]@{outcome="passed";status="production_ready";capability=$rep;markerLast=$true})
$gold=Ev "golden-parity" "golden_parity" ([ordered]@{outcome="passed";assertionCount=4;normalizedA00Parity=$true;command="scripts/tests/test-dag-facade.ps1 + marker-last A07 test"})
$contract=Ev "contract-parity" "contract_parity" ([ordered]@{outcome="blocked";assertionCount=7;a07PhaseMatrix="passed_internal";facadeFailureMatrix="blocked_no_public_injection";a09ToA07Connected=$boundary.a09ToA07Connected;blocker="normal facade A09 handoff is not yet routed into A07"})
$effects=Ev "effect-parity" "effect_parity" ([ordered]@{outcome="blocked";assertionCount=3;declaredEffects=@("local_write");indexTraversalChanged=$false;blocker="end-to-end A09 to A07 effect parity is not yet available"})
$registry=Ev "registry-reconciliation" "registry_reconciliation" ([ordered]@{outcome="passed";registryParticipantId="facade.publication.legacy-staging-marker";replacementCapabilityId=$rep;status="declared";indexTraversalExcluded=$true})
$window=Ev "compatibility-window" "compatibility_window" ([ordered]@{outcome="blocked";startedAt=$EvaluatedAt;observedThrough=$EvaluatedAt;minimumDays=30;checkedAt=$EvaluatedAt;expiresAt=$expiry;blocker="no completed 30-day window"})
$rr="work/e05-publication-rollback-$EvaluatedAt";$rollbackCommand="pwsh -NoLogo -NoProfile -File tools/compatibility/Restore-PublicationLegacyBranch.ps1 -RehearsalRoot $rr"
$rollbackResult=& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "tools\compatibility\Restore-PublicationLegacyBranch.ps1") -RehearsalRoot (Join-Path $RepoRoot ($rr-replace'/',[IO.Path]::DirectorySeparatorChar))|ConvertFrom-Json;if($LASTEXITCODE-ne0-or$rollbackResult.exactReplay-ne$true){throw "rollback failed"}
$rollback=Ev "rollback-execution" "rollback_execution" ([ordered]@{outcome="passed";command=$rollbackCommand;executedAt=$EvaluatedAt;exitCode=0;target="$rr/run-code-intel.ps1";exactReplay=$rollbackResult.exactReplay;sourceSha256=$rollbackResult.sourceSha256;targetSha256=$rollbackResult.targetSha256;replacementChanged=$false;indexTraversalChanged=$false})
$usage=Ev "usage-observation" "usage_observation" ([ordered]@{outcome="blocked";startedAt=$EvaluatedAt;endedAt=$EvaluatedAt;totalInvocations=0;legacyInvocations=0;replacementInvocations=0;blocker="no production usage observation"})
$trace='{"legacyBranchId":"'+$bid+'","replacementCapabilityId":"'+$rep+'","retirementId":"'+$rid+'"}'
$necessity=Ev "c00-necessity" "c00_necessity" ([ordered]@{outcome="passed";decision="admit";changeId=$rid;necessityTraceSha256=(ShaText $trace)})
$a09=Ev "dependency-a09" "dependency_approval" ([ordered]@{outcome="blocked";dependencyId="run.dag-coordinate";status="pending";reviewer="route-verifier-required";blocker="A09 handoff is not connected to A07"})
$a06=Ev "dependency-a06-stage" "dependency_approval" ([ordered]@{outcome="passed";dependencyId="artifact.stage-transaction";status="approved";reviewer="e05-author"})
$subject=[ordered]@{legacyBranch=[ordered]@{capabilityId="facade.publication.legacy-staging-marker";branchId=$bid;callPath=$call;affectedFiles=@("run-code-intel.ps1");owner="executor-publication";registryParticipantId="facade.publication.legacy-staging-marker"};replacement=[ordered]@{capabilityId=$rep;implementationId="run.commit.compat";dependencies=@("run.dag-coordinate","artifact.stage-transaction");atomEvidence=$atom};parity=[ordered]@{golden=$gold;contract=$contract;effects=$effects};registryReconciliation=$registry;compatibilityWindow=$window;rollback=[ordered]@{command=$rollbackCommand;executionEvidence=$rollback};usageObservation=$usage;necessityEvidence=$necessity;dependencyStates=@($a09,$a06);lineReductionEvidence=$false}
$independent=Ev "independent-approval" "independent_approval" ([ordered]@{outcome="blocked";approved=$false;authorIndependent=$false;subjectSha256=("0"*64);reviewer="independent-verifier-required";authorityEvent=[ordered]@{};blocker="no independent approval"})
$manifest=[ordered]@{schema="code-intel-compatibility-retirement-manifest.v1";snapshotIdentity=$snapshot;retirementId=$rid;approvalSubject=$subject;independentApproval=$independent};Write-Json (Join-Path $OutDir "compatibility-retirement-manifest.json") $manifest;$manifestRef=Ref "code-intel-compatibility-retirement-manifest.v1" "compatibility.retirement-manifest" "compatibility-retirement-manifest.json"
$registryJson=Get-Content (Join-Path $RepoRoot "orchestration\integrations.json") -Raw|ConvertFrom-Json;$gateDecl=($registryJson.integrations|Where-Object id -eq "compatibility.retirement-gate").capabilityDeclaration
$gate=[ordered]@{schema="code-intel-capability-request.v1";capability="compatibility.retirement-gate";contractVersion=1;implementation=$gateDecl.implementation;snapshot=[ordered]@{identity=$snapshot;repoIdentity=("content-v1:"+("c"*64));head="working-tree-e05";workingTreePolicy="explicit_overlay";scope=@(".");inputDigest=("d"*64)};options=[ordered]@{evaluatedAt=$EvaluatedAt};inputs=@($manifestRef,$atom,$gold,$contract,$effects,$registry,$window,$rollback,$usage,$necessity,$a09,$a06,$independent);effectPolicy=[ordered]@{allowedEffects=$gateDecl.allowedEffects}}
Write-Json (Join-Path $OutDir "e00-request.json") $gate;$gateOut=Join-Path $OutDir "gate-out";& $CodeIntel capability exec compatibility.retirement-gate --request (Join-Path $OutDir "e00-request.json") --out $gateOut --artifact-root $OutDir|Out-Null;if($LASTEXITCODE-ne0){throw "E00 failed"};$decision=Get-Content (Join-Path $gateOut "compatibility-retirement-decision.json") -Raw|ConvertFrom-Json;if($decision.decision-ne"blocked"){throw "E05 must remain blocked"}
$deleted=0;$hunks=@($matches|ForEach-Object{$value=$_.Value;$lines=@($value-split"`n");$old=@($base.Substring(0,$_.Index)-split"`n").Count;$h=[ordered]@{addedLines=@();deletedLines=$lines;newLines=0;newStart=$old-$deleted;oldLines=$lines.Count;oldStart=$old};$deleted+=$lines.Count;$h})
$baseLines=@($base-split"`n");$resultLines=for($i=1;$i-le$baseLines.Count;$i++){if(-not@($hunks|Where-Object{$i-ge$_.oldStart-and$i-lt($_.oldStart+$_.oldLines)}).Count){$baseLines[$i-1]}};$result=$resultLines-join"`n"
$files=@([ordered]@{baseBlobSha256=(ShaText $base);baseText=$base;hunks=$hunks;path="run-code-intel.ps1";resultBlobSha256=(ShaText $result);resultText=$result})
$diff=[ordered]@{schema="code-intel-compatibility-retirement-deletion-diff.v1";snapshotIdentity=$snapshot;retirementId=$rid;legacyBranchId=$bid;affectedFiles=@("run-code-intel.ps1");deletionsOnly=$true;summary="Two-hunk deletion is limited to legacy staging allocation and promotion/completion marker; artifact generation and all index traversal are excluded.";patch=[ordered]@{algorithm="replayable-delete-only-v1";sha256=(ShaText (ConvertTo-Json -InputObject $files -Depth 30 -Compress));files=$files}}
Write-Json (Join-Path $OutDir "compatibility-retirement-deletion-diff.json") $diff;$diffRef=Ref "code-intel-compatibility-retirement-deletion-diff.v1" "compatibility.retirement-deletion-diff" "compatibility-retirement-deletion-diff.json";$decisionRef=Ref "code-intel-compatibility-retirement-decision.v1" "compatibility.retirement-decision" "gate-out/compatibility-retirement-decision.json"
$ticket=[ordered]@{schema="code-intel-compatibility-retirement-ticket-template.v1";snapshotIdentity=$snapshot;ticketId="ticket-e05-retire-publication-branch";retirementId=$rid;legacyBranch=[ordered]@{capabilityId="facade.publication.legacy-staging-marker";branchId=$bid;callPath=$call};replacement=[ordered]@{capabilityId=$rep;dependencies=@("run.dag-coordinate","artifact.stage-transaction")};affectedFiles=@("run-code-intel.ps1");evidence=[ordered]@{golden=$gold;contract=$contract;effects=$effects;usage=$usage;rollbackRehearsal=$rollback;deletionDiff=$diffRef};source=[ordered]@{retirementDecision=$decisionRef;retirementManifest=$manifestRef};owner="executor-publication";verifier="independent-verifier-required";observationExpiry=$expiry;status="draft";authorityBoundary="template_only_no_approval_or_deletion_authority"}
Write-Json (Join-Path $OutDir "compatibility-retirement-ticket.json") $ticket;& $CodeIntel compatibility retirement-ticket lint --ticket (Join-Path $OutDir "compatibility-retirement-ticket.json") --evaluated-at $EvaluatedAt|Out-Null;if($LASTEXITCODE-ne0){throw "E01 lint failed"};$ticketRef=Ref "code-intel-compatibility-retirement-ticket-template.v1" "compatibility.retirement-ticket-template" "compatibility-retirement-ticket.json";$ticketDecl=($registryJson.integrations|Where-Object id -eq "compatibility.retirement-ticket-template").capabilityDeclaration
$e01=[ordered]@{schema="code-intel-capability-request.v1";capability="compatibility.retirement-ticket-template";contractVersion=1;implementation=$ticketDecl.implementation;snapshot=$gate.snapshot;options=[ordered]@{evaluatedAt=$EvaluatedAt};inputs=@($ticketRef,$manifestRef,$decisionRef,$diffRef);effectPolicy=[ordered]@{allowedEffects=$ticketDecl.allowedEffects}};Write-Json (Join-Path $OutDir "e01-request.json") $e01
$o=@(& $CodeIntel capability exec compatibility.retirement-ticket-template --request (Join-Path $OutDir "e01-request.json") --out (Join-Path $OutDir "e01-out") --artifact-root $OutDir 2>&1);$x=$LASTEXITCODE;$txt=$o-join"`n";[IO.File]::WriteAllText((Join-Path $OutDir "e01-stderr.txt"),$txt,[Text.UTF8Encoding]::new($false));if($x-ne65-or$txt-notmatch"ticket requires an approved E00 decision"){throw "E01 must validate patch then reject blocked E00: $x $txt"}
if((Get-FileHash $indexPath -Algorithm SHA256).Hash.ToLowerInvariant()-ne$indexHash){throw "E05 changed index traversal"}
$status=[ordered]@{schema="code-intel-compatibility-retirement-execution-status.v1";retirementId=$rid;decision="blocked";deletionExecuted=$false;retired=$false;blockers=@($decision.blockers);gainLedgerProjection=$decision.gainLedgerProjection;boundary="A09 is not yet connected to A07 and facade phase injection is absent; E05 has no deletion authority and excludes E10."};Write-Json (Join-Path $OutDir "status.json") $status;$status|ConvertTo-Json -Depth 10 -Compress
