[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$OutDir,[Parameter(Mandatory=$true)][long]$EvaluatedAt,[string]$RepoRoot=(Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),[string]$CodeIntel=(Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) "target\debug\code-intel.exe"))
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop";if($EvaluatedAt-le0){throw "bad time"};if(Test-Path $OutDir){throw "exclusive output required"};if(-not(Test-Path $CodeIntel -PathType Leaf)){throw "binary missing"};New-Item -ItemType Directory $OutDir|Out-Null;New-Item -ItemType Directory (Join-Path $OutDir evidence)|Out-Null
function W([string]$p,[object]$v){[IO.File]::WriteAllText($p,($v|ConvertTo-Json -Depth 40 -Compress),[Text.UTF8Encoding]::new($false))};function S([string]$t){([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($t)))).ToLowerInvariant()};function Ref([string]$s,[string]$t,[string]$r){$p=Join-Path $OutDir ($r-replace'/',[IO.Path]::DirectorySeparatorChar);[ordered]@{schema="code-intel-artifact-ref.v1";artifactSchema=$s;type=$t;path=($r-replace'\\','/');sha256=((Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant());consumedSnapshotIdentity=$snapshot}}
$tests=@('complete_and_staged_side_by_side_indexes_only_complete_run','forged_marker_manifest_and_artifact_bindings_are_diagnosed_and_rejected','incomplete_and_legacy_runs_are_diagnostic_only_and_newer_invalid_does_not_win','rebuild_and_incremental_are_byte_equivalent_and_stably_sorted','production_cli_writes_the_registered_committed_only_schema');foreach($n in $tests){& cargo test -q -p code-intel --test artifact_index $n -- --exact|Out-Null;if($LASTEXITCODE-ne0){throw "A08 test failed $n"}}
$facade=& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "scripts/tests/test-artifact-index-contract.ps1")|ConvertFrom-Json;if($facade.productionSchema-ne"code-intel-artifact-index.v1"){throw "A08 facade contract failed"}
$boundary=& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "tools\compatibility\Test-IndexRetirementBoundary.ps1")|ConvertFrom-Json;$indexPath=Join-Path $RepoRoot "update-code-intel-index.ps1";$source=[IO.File]::ReadAllText($indexPath);$base=$source.Replace("`r`n","`n").Replace("`r","`n");$pattern='(?s)function Read-JsonFile \{.*\z';$match=[regex]::Match($base,$pattern);if(-not$match.Success){throw "E10 branch absent"}
$frozen=@('update-code-intel-index.ps1','crates/code-intel-cli/src/artifact_index.rs','crates/code-intel-cli/tests/artifact_index.rs','crates/code-intel-cli/src/run_commit.rs','orchestration/integrations.json','orchestration/retirements/e05-publication/status.json','orchestration/retirements/e05-publication/gate-out/compatibility-retirement-decision.json');$digests=@{};foreach($p in $frozen){$digests[$p]=(Get-FileHash (Join-Path $RepoRoot $p)-Algorithm SHA256).Hash.ToLowerInvariant()};$snapshot=S (($frozen|ForEach-Object{$digests[$_]})-join"`n")
$rid="retire-index-branch";$bid="update-code-intel-index.legacy-compatibility-traversal";$rep="artifact.index-committed-only";$call="update-code-intel-index.ps1::$bid";$expiry=$EvaluatedAt+2592000
function E([string]$n,[string]$c,[object]$d){$v=[ordered]@{schema="code-intel-compatibility-retirement-evidence.v1";snapshotIdentity=$snapshot;id="e10.$n";evidenceClass=$c;retirementId=$rid;legacyBranchId=$bid;replacementCapabilityId=$rep;details=$d};$r="evidence/$n.json";W (Join-Path $OutDir $r) $v;Ref "code-intel-compatibility-retirement-evidence.v1" "compatibility.retirement-evidence" $r}
$atom=E "replacement-atom" "replacement_atom" ([ordered]@{outcome="passed";status="production_ready";capability=$rep;publicNormalUsesA08=$boundary.publicNormalUsesA08;normalSchema="code-intel-artifact-index.v1"})
$gold=E "golden-parity" "golden_parity" ([ordered]@{outcome="passed";assertionCount=6;executedRustTests=$tests.Count;executedPowerShellTests=1;validOnlyAdmission=$true;stagingRejected=$true;markerlessRejected=$true;forgedRejected=$true})
$contract=E "contract-parity" "contract_parity" ([ordered]@{outcome="passed";assertionCount=6;rebuildIncrementalByteEquivalent=$true;latestValidWins=$true;dirtyStagingGuard=$true;markerGuard=$true})
$effects=E "effect-parity" "effect_parity" ([ordered]@{outcome="passed";assertionCount=4;declaredEffects=@("repo_read","local_write");authoritativeSchema="code-intel-artifact-index.v1";legacyOutputDiagnosticOnly=$true;legacyCanWriteAuthoritativeIndex=$false})
$registry=E "registry-reconciliation" "registry_reconciliation" ([ordered]@{outcome="passed";registryParticipantId=$rep;replacementCapabilityId=$rep;status="declared";publicNormalUsesA08=$true;publicLegacyRouteReachable=$true})
$window=E "compatibility-window" "compatibility_window" ([ordered]@{outcome="blocked";startedAt=$EvaluatedAt;observedThrough=$EvaluatedAt;minimumDays=30;checkedAt=$EvaluatedAt;expiresAt=$expiry;blocker="no completed post-A08 public-route observation window"})
$rr="work/e10-index-rollback-$EvaluatedAt";$rc="pwsh -NoLogo -NoProfile -File tools/compatibility/Restore-IndexLegacyBranch.ps1 -RehearsalRoot $rr";$rb=& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "tools\compatibility\Restore-IndexLegacyBranch.ps1") -RehearsalRoot (Join-Path $RepoRoot ($rr-replace'/',[IO.Path]::DirectorySeparatorChar))|ConvertFrom-Json;if($LASTEXITCODE-ne0-or$rb.exactReplay-ne$true){throw "rollback failed"}
$rollback=E "rollback-execution" "rollback_execution" ([ordered]@{outcome="passed";command=$rc;executedAt=$EvaluatedAt;exitCode=0;target="$rr/update-code-intel-index.ps1";exactReplay=$rb.exactReplay;sourceSha256=$rb.sourceSha256;targetSha256=$rb.targetSha256;a08Changed=$false;e05Changed=$false})
$usage=E "usage-observation" "usage_observation" ([ordered]@{outcome="blocked";startedAt=$EvaluatedAt;endedAt=$EvaluatedAt;totalInvocations=0;legacyInvocations=0;replacementInvocations=0;blocker="production observation has not completed"})
$trace='{"legacyBranchId":"'+$bid+'","replacementCapabilityId":"'+$rep+'","retirementId":"'+$rid+'"}';$necessity=E "c00-necessity" "c00_necessity" ([ordered]@{outcome="passed";decision="admit";changeId=$rid;necessityTraceSha256=(S $trace)})
$e05=E "dependency-e05" "dependency_approval" ([ordered]@{outcome="blocked";dependencyId="compatibility.retire-publication-branch";status="pending";reviewer="e05-gate";blocker="E05 publication retirement remains blocked"})
$subject=[ordered]@{legacyBranch=[ordered]@{capabilityId="artifact.index.legacy-powershell";branchId=$bid;callPath=$call;affectedFiles=@("update-code-intel-index.ps1");owner="executor-index";registryParticipantId=$rep};replacement=[ordered]@{capabilityId=$rep;implementationId="artifact.index-committed-only.compat";dependencies=@("compatibility.retire-publication-branch");atomEvidence=$atom};parity=[ordered]@{golden=$gold;contract=$contract;effects=$effects};registryReconciliation=$registry;compatibilityWindow=$window;rollback=[ordered]@{command=$rc;executionEvidence=$rollback};usageObservation=$usage;necessityEvidence=$necessity;dependencyStates=@($e05);lineReductionEvidence=$false}
$independent=E "independent-approval" "independent_approval" ([ordered]@{outcome="blocked";approved=$false;authorIndependent=$false;subjectSha256=("0"*64);reviewer="independent-verifier-required";authorityEvent=[ordered]@{};blocker="no independent approval"});$manifest=[ordered]@{schema="code-intel-compatibility-retirement-manifest.v1";snapshotIdentity=$snapshot;retirementId=$rid;approvalSubject=$subject;independentApproval=$independent};W (Join-Path $OutDir "compatibility-retirement-manifest.json") $manifest;$manifestRef=Ref "code-intel-compatibility-retirement-manifest.v1" "compatibility.retirement-manifest" "compatibility-retirement-manifest.json"
$registryJson=Get-Content (Join-Path $RepoRoot "orchestration\integrations.json") -Raw|ConvertFrom-Json;$gateDecl=($registryJson.integrations|Where-Object id -eq "compatibility.retirement-gate").capabilityDeclaration;$requestSnapshot=[ordered]@{identity=$snapshot;repoIdentity=("content-v1:"+("c"*64));head="working-tree-e10";workingTreePolicy="explicit_overlay";scope=@(".");inputDigest=("d"*64)}
$gate=[ordered]@{schema="code-intel-capability-request.v1";capability="compatibility.retirement-gate";contractVersion=1;implementation=$gateDecl.implementation;snapshot=$requestSnapshot;options=[ordered]@{evaluatedAt=$EvaluatedAt};inputs=@($manifestRef,$atom,$gold,$contract,$effects,$registry,$window,$rollback,$usage,$necessity,$e05,$independent);effectPolicy=[ordered]@{allowedEffects=$gateDecl.allowedEffects}};W (Join-Path $OutDir "e00-request.json") $gate;$gateOut=Join-Path $OutDir "gate-out";& $CodeIntel capability exec compatibility.retirement-gate --request (Join-Path $OutDir "e00-request.json") --out $gateOut --artifact-root $OutDir|Out-Null;if($LASTEXITCODE-ne0){throw "E00 failed"};$decision=Get-Content (Join-Path $gateOut "compatibility-retirement-decision.json") -Raw|ConvertFrom-Json;if($decision.decision-ne"blocked"){throw "E10 must remain blocked"}
$baseLines=@($base-split"`n");$oldStart=@($base.Substring(0,$match.Index)-split"`n").Count;$lines=@($baseLines[($oldStart-1)..($baseLines.Count-1)]);$hunk=[ordered]@{addedLines=@();deletedLines=$lines;newLines=0;newStart=$oldStart;oldLines=$lines.Count;oldStart=$oldStart};$result=@($baseLines[0..($oldStart-2)])-join"`n";$files=@([ordered]@{baseBlobSha256=(S $base);baseText=$base;hunks=@($hunk);path="update-code-intel-index.ps1";resultBlobSha256=(S $result);resultText=$result});$diff=[ordered]@{schema="code-intel-compatibility-retirement-deletion-diff.v1";snapshotIdentity=$snapshot;retirementId=$rid;legacyBranchId=$bid;affectedFiles=@("update-code-intel-index.ps1");deletionsOnly=$true;summary="One-hunk deletion removes only explicit legacy index traversal; A08 normal route and E05 publication branch are excluded.";patch=[ordered]@{algorithm="replayable-delete-only-v1";sha256=(S (ConvertTo-Json -InputObject $files -Depth 40 -Compress));files=$files}};W (Join-Path $OutDir "compatibility-retirement-deletion-diff.json") $diff;$diffRef=Ref "code-intel-compatibility-retirement-deletion-diff.v1" "compatibility.retirement-deletion-diff" "compatibility-retirement-deletion-diff.json";$decisionRef=Ref "code-intel-compatibility-retirement-decision.v1" "compatibility.retirement-decision" "gate-out/compatibility-retirement-decision.json"
$ticket=[ordered]@{schema="code-intel-compatibility-retirement-ticket-template.v1";snapshotIdentity=$snapshot;ticketId="ticket-e10-retire-index-branch";retirementId=$rid;legacyBranch=[ordered]@{capabilityId="artifact.index.legacy-powershell";branchId=$bid;callPath=$call};replacement=[ordered]@{capabilityId=$rep;dependencies=@("compatibility.retire-publication-branch")};affectedFiles=@("update-code-intel-index.ps1");evidence=[ordered]@{golden=$gold;contract=$contract;effects=$effects;usage=$usage;rollbackRehearsal=$rollback;deletionDiff=$diffRef};source=[ordered]@{retirementDecision=$decisionRef;retirementManifest=$manifestRef};owner="executor-index";verifier="independent-verifier-required";observationExpiry=$expiry;status="draft";authorityBoundary="template_only_no_approval_or_deletion_authority"};W (Join-Path $OutDir "compatibility-retirement-ticket.json") $ticket;& $CodeIntel compatibility retirement-ticket lint --ticket (Join-Path $OutDir "compatibility-retirement-ticket.json") --evaluated-at $EvaluatedAt|Out-Null;if($LASTEXITCODE-ne0){throw "E01 lint failed"};$ticketRef=Ref "code-intel-compatibility-retirement-ticket-template.v1" "compatibility.retirement-ticket-template" "compatibility-retirement-ticket.json";$ticketDecl=($registryJson.integrations|Where-Object id -eq "compatibility.retirement-ticket-template").capabilityDeclaration
$e01=[ordered]@{schema="code-intel-capability-request.v1";capability="compatibility.retirement-ticket-template";contractVersion=1;implementation=$ticketDecl.implementation;snapshot=$requestSnapshot;options=[ordered]@{evaluatedAt=$EvaluatedAt};inputs=@($ticketRef,$manifestRef,$decisionRef,$diffRef);effectPolicy=[ordered]@{allowedEffects=$ticketDecl.allowedEffects}};W (Join-Path $OutDir "e01-request.json") $e01;$o=@(& $CodeIntel capability exec compatibility.retirement-ticket-template --request (Join-Path $OutDir "e01-request.json") --out (Join-Path $OutDir "e01-out") --artifact-root $OutDir 2>&1);$x=$LASTEXITCODE;$txt=$o-join"`n";[IO.File]::WriteAllText((Join-Path $OutDir "e01-stderr.txt"),$txt,[Text.UTF8Encoding]::new($false));if($x-ne65-or$txt-notmatch"ticket requires an approved E00 decision"){throw "E01 boundary failed"}
foreach($p in $frozen){if((Get-FileHash (Join-Path $RepoRoot $p)-Algorithm SHA256).Hash.ToLowerInvariant()-ne$digests[$p]){throw "E10 changed frozen path $p"}};$status=[ordered]@{schema="code-intel-compatibility-retirement-execution-status.v1";retirementId=$rid;decision="blocked";publicNormalUsesA08=$true;publicLegacyRouteReachable=$true;legacyOutputDiagnosticOnly=$true;legacyCanWriteAuthoritativeIndex=$false;e05Decision="blocked";deletionExecuted=$false;retired=$false;blockers=@($decision.blockers);gainLedgerProjection=$decision.gainLedgerProjection;boundary="A08 owns normal authoritative indexing, but E05, observation, and independent approval remain blocked; no deletion authority exists."};W (Join-Path $OutDir "status.json") $status;$status|ConvertTo-Json -Depth 10 -Compress
