[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$OutDir,[Parameter(Mandatory=$true)][long]$EvaluatedAt,[string]$RepoRoot=(Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),[string]$CodeIntel=(Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) "target\debug\code-intel.exe"))
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop";if($EvaluatedAt-le0){throw "bad time"};if(Test-Path $OutDir){throw "exclusive output required"};if(-not(Test-Path $CodeIntel -PathType Leaf)){throw "binary missing"};New-Item -ItemType Directory $OutDir|Out-Null;New-Item -ItemType Directory (Join-Path $OutDir evidence)|Out-Null
function W([string]$p,[object]$v){[IO.File]::WriteAllText($p,($v|ConvertTo-Json -Depth 40 -Compress),[Text.UTF8Encoding]::new($false))};function S([string]$t){([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($t)))).ToLowerInvariant()};function Ref([string]$s,[string]$t,[string]$r){$p=Join-Path $OutDir ($r-replace'/',[IO.Path]::DirectorySeparatorChar);[ordered]@{schema="code-intel-artifact-ref.v1";artifactSchema=$s;type=$t;path=($r-replace'\\','/');sha256=((Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant());consumedSnapshotIdentity=$snapshot}}
$invokePath=Join-Path $RepoRoot "invoke-code-intel.ps1";$base=[IO.File]::ReadAllText($invokePath).Replace("`r`n","`n").Replace("`r","`n");$patterns=@('(?m)^\$doctor = Join-Path \$root "check-code-intel-tools\.ps1"$','(?sm)^    Write-Host "Code intel invoke: doctor \$label".*?^    \}(?=\n\n    Write-Host "Code intel invoke: pipeline \$label")','(?sm)^if \(-not \(Test-Path -LiteralPath \$doctor -PathType Leaf\)\) \{\n    throw "Doctor script missing: \$doctor"\n\}')
$routeMatches=@($patterns|ForEach-Object{$all=[regex]::Matches($base,$_);if($all.Count-ne1){throw "E09 route marker absent or ambiguous: $_"};$all[0]}|Sort-Object Index)
$checkPath=Join-Path $RepoRoot "check-code-intel-tools.ps1";$checkHash=(Get-FileHash $checkPath -Algorithm SHA256).Hash.ToLowerInvariant();$registry=Get-Content (Join-Path $RepoRoot "orchestration/integrations.json") -Raw|ConvertFrom-Json;$doctor=@($registry.integrations|Where-Object id -eq doctor);if($doctor.Count-ne1-or$doctor[0].owner-ne"code-intel-pipeline"){throw "B07 doctor ownership missing"};$extension=[string]$doctor[0].extensionPoint;$nonAuthoritative=$extension-match'observation-only bootstrap';$expiryDeclared=$extension-match'expir|sunset|remove-after'
$tests=@('doctor_cli_emits_one_envelope_and_snapshot_bound_redacted_observation','doctor_cli_fails_closed_without_verified_snapshot_input','doctor_cli_reports_nonconforming_provider_and_manifest_drift_as_domain_failure');foreach($n in $tests){& cargo test -q -p code-intel --test doctor_envelope $n -- --exact|Out-Null;if($LASTEXITCODE-ne0){throw "B10 test failed $n"}}
$audit=& $CodeIntel orchestrate --action Validate --manifest (Join-Path $RepoRoot "orchestration/integrations.json") --json|ConvertFrom-Json;if(-not$audit.ok-or-not$audit.registryAudit.ok){throw "B07 audit failed"}
$frozen=@('invoke-code-intel.ps1','check-code-intel-tools.ps1','crates/code-intel-cli/src/doctor_adapter.rs','crates/code-intel-cli/tests/doctor_envelope.rs','crates/code-intel-cli/src/dag_run.rs','orchestration/integrations.json');$snapshot=S (($frozen|ForEach-Object{(Get-FileHash (Join-Path $RepoRoot $_) -Algorithm SHA256).Hash.ToLowerInvariant()})-join"`n")
$rid="retire-doctor-wrapper-branch";$bid="invoke-code-intel.doctor.direct-production";$rep="doctor";$call="invoke-code-intel.ps1::$bid";$expiry=$EvaluatedAt+2592000
function E([string]$n,[string]$c,[object]$d){$v=[ordered]@{schema="code-intel-compatibility-retirement-evidence.v1";snapshotIdentity=$snapshot;id="e09.$n";evidenceClass=$c;retirementId=$rid;legacyBranchId=$bid;replacementCapabilityId=$rep;details=$d};$r="evidence/$n.json";W (Join-Path $OutDir $r) $v;Ref "code-intel-compatibility-retirement-evidence.v1" "compatibility.retirement-evidence" $r}
$atom=E "replacement-atom" "replacement_atom" ([ordered]@{outcome="blocked";status="pending_public_preflight_route_and_bootstrap_expiry";capability=$rep;b10EnvelopeAvailable=$true;publicWrapperUsesDirectDoctor=$true;retainedBootstrap="check-code-intel-tools.ps1";bootstrapNonAuthoritative=$nonAuthoritative;bootstrapRegistered=$true;bootstrapOwner="code-intel-pipeline";bootstrapExpiryDeclared=$expiryDeclared;blocker="public preflight still invokes the bootstrap directly and retained bootstrap has no explicit expiry"})
$gold=E "golden-parity" "golden_parity" ([ordered]@{outcome="passed";assertionCount=3;executedTestCount=$tests.Count;singleResultDocument=$true;manifestDriftFixture=$true;presentNonconformingFixture=$true;testFunctions=$tests})
$contract=E "contract-parity" "contract_parity" ([ordered]@{outcome="passed";assertionCount=5;readinessConformanceSeparated=$true;admissibilityNotPromoted=$true;domainFailureNonzero=$true;snapshotInputRequired=$true;stdoutDocumentCount=1})
$effects=E "effect-parity" "effect_parity" ([ordered]@{outcome="passed";assertionCount=4;declaredEffects=@("repo_read","local_write");transport="artifact_ref";secretRedacted=$true;bootstrapProbeEffect="observation_only"})
$registryEv=E "registry-reconciliation" "registry_reconciliation" ([ordered]@{outcome="passed";registryParticipantId="doctor";replacementCapabilityId=$rep;status="declared";registryAuditOk=$true;owner="code-intel-pipeline";directRouteSegments=3;bootstrapHash=$checkHash})
$window=E "compatibility-window" "compatibility_window" ([ordered]@{outcome="blocked";startedAt=$EvaluatedAt;observedThrough=$EvaluatedAt;minimumDays=30;checkedAt=$EvaluatedAt;expiresAt=$expiry;blocker="no completed B10 public-preflight observation window"})
$rr="rollback-rehearsal";$rc="pwsh -NoProfile -File tools/compatibility/Restore-DoctorWrapperBranch.ps1 -RehearsalRoot <packet-root>/$rr";& pwsh -NoProfile -File (Join-Path $RepoRoot "tools/compatibility/Restore-DoctorWrapperBranch.ps1") -RehearsalRoot (Join-Path $OutDir $rr)|Out-Null;if($LASTEXITCODE-ne0){throw "rollback failed"};$rollback=E "rollback-execution" "rollback_execution" ([ordered]@{outcome="passed";command=$rc;executedAt=$EvaluatedAt;exitCode=0;target="$rr/invoke-code-intel.ps1";exactReplay=$true;bootstrapChanged=$false;otherWrapperBranchesChanged=$false})
$usage=E "usage-observation" "usage_observation" ([ordered]@{outcome="blocked";startedAt=$EvaluatedAt;endedAt=$EvaluatedAt;totalInvocations=0;legacyInvocations=0;replacementInvocations=0;blocker="public B10 usage observation has not started"})
$trace='{"legacyBranchId":"'+$bid+'","replacementCapabilityId":"'+$rep+'","retirementId":"'+$rid+'"}';$necessity=E "c00-necessity" "c00_necessity" ([ordered]@{outcome="passed";decision="admit";changeId=$rid;necessityTraceSha256=(S $trace);rationale="remove authoritative direct wrapper routing without deleting fresh-machine bootstrap"})
$dep=E "dependency-snapshot" "dependency_approval" ([ordered]@{outcome="passed";dependencyId="repo.snapshot";status="approved";reviewer="e09-author"})
$subject=[ordered]@{legacyBranch=[ordered]@{capabilityId="doctor.bootstrap.direct-production";branchId=$bid;callPath=$call;affectedFiles=@("invoke-code-intel.ps1");owner="executor-doctor-wrapper";registryParticipantId="doctor"};replacement=[ordered]@{capabilityId=$rep;implementationId="doctor.envelope.compat";dependencies=@("repo.snapshot");atomEvidence=$atom};parity=[ordered]@{golden=$gold;contract=$contract;effects=$effects};registryReconciliation=$registryEv;compatibilityWindow=$window;rollback=[ordered]@{command=$rc;executionEvidence=$rollback};usageObservation=$usage;necessityEvidence=$necessity;dependencyStates=@($dep);lineReductionEvidence=$false}
$ind=E "independent-approval" "independent_approval" ([ordered]@{outcome="blocked";approved=$false;authorIndependent=$false;subjectSha256=("0"*64);reviewer="independent-verifier-required";authorityEvent=[ordered]@{};blocker="no independent approval"});$manifest=[ordered]@{schema="code-intel-compatibility-retirement-manifest.v1";snapshotIdentity=$snapshot;retirementId=$rid;approvalSubject=$subject;independentApproval=$ind};W (Join-Path $OutDir "compatibility-retirement-manifest.json") $manifest;$manifestRef=Ref "code-intel-compatibility-retirement-manifest.v1" "compatibility.retirement-manifest" "compatibility-retirement-manifest.json"
$gateDecl=($registry.integrations|Where-Object id -eq "compatibility.retirement-gate").capabilityDeclaration;$snap=[ordered]@{identity=$snapshot;repoIdentity=("content-v1:"+("c"*64));head="working-tree-e09";workingTreePolicy="explicit_overlay";scope=@(".");inputDigest=("d"*64)};$gate=[ordered]@{schema="code-intel-capability-request.v1";capability="compatibility.retirement-gate";contractVersion=1;implementation=$gateDecl.implementation;snapshot=$snap;options=[ordered]@{evaluatedAt=$EvaluatedAt};inputs=@($manifestRef,$atom,$gold,$contract,$effects,$registryEv,$window,$rollback,$usage,$necessity,$dep,$ind);effectPolicy=[ordered]@{allowedEffects=$gateDecl.allowedEffects}};W (Join-Path $OutDir "e00-request.json") $gate;$gateOut=Join-Path $OutDir gate-out;& $CodeIntel capability exec compatibility.retirement-gate --request (Join-Path $OutDir "e00-request.json") --out $gateOut --artifact-root $OutDir|Out-Null;if($LASTEXITCODE-ne0){throw "E00 failed"};$decision=Get-Content (Join-Path $gateOut "compatibility-retirement-decision.json") -Raw|ConvertFrom-Json;if($decision.decision-ne"blocked"){throw "E09 must remain blocked"}
$deleted=0;$hunks=@($routeMatches|ForEach-Object{$lines=@($_.Value-split"`n");$old=@($base.Substring(0,$_.Index)-split"`n").Count;$h=[ordered]@{addedLines=@();deletedLines=$lines;newLines=0;newStart=$old-$deleted;oldLines=$lines.Count;oldStart=$old};$deleted+=$lines.Count;$h});$baseLines=@($base-split"`n");$resultLines=for($i=1;$i-le$baseLines.Count;$i++){if(-not@($hunks|Where-Object{$i-ge$_.oldStart-and$i-lt($_.oldStart+$_.oldLines)}).Count){$baseLines[$i-1]}};$result=$resultLines-join"`n";$files=@([ordered]@{baseBlobSha256=(S $base);baseText=$base;hunks=$hunks;path="invoke-code-intel.ps1";resultBlobSha256=(S $result);resultText=$result});$diff=[ordered]@{schema="code-intel-compatibility-retirement-deletion-diff.v1";snapshotIdentity=$snapshot;retirementId=$rid;legacyBranchId=$bid;affectedFiles=@("invoke-code-intel.ps1");deletionsOnly=$true;summary="Three-hunk draft removes only direct production doctor routing; check-code-intel-tools.ps1 bootstrap is retained.";patch=[ordered]@{algorithm="replayable-delete-only-v1";sha256=(S (ConvertTo-Json -InputObject $files -Depth 40 -Compress));files=$files}};W (Join-Path $OutDir "compatibility-retirement-deletion-diff.json") $diff;$diffRef=Ref "code-intel-compatibility-retirement-deletion-diff.v1" "compatibility.retirement-deletion-diff" "compatibility-retirement-deletion-diff.json";$decisionRef=Ref "code-intel-compatibility-retirement-decision.v1" "compatibility.retirement-decision" "gate-out/compatibility-retirement-decision.json"
$ticket=[ordered]@{schema="code-intel-compatibility-retirement-ticket-template.v1";snapshotIdentity=$snapshot;ticketId="ticket-e09-retire-doctor-wrapper-branch";retirementId=$rid;legacyBranch=[ordered]@{capabilityId="doctor.bootstrap.direct-production";branchId=$bid;callPath=$call};replacement=[ordered]@{capabilityId=$rep;dependencies=@("repo.snapshot")};affectedFiles=@("invoke-code-intel.ps1");evidence=[ordered]@{golden=$gold;contract=$contract;effects=$effects;usage=$usage;rollbackRehearsal=$rollback;deletionDiff=$diffRef};source=[ordered]@{retirementDecision=$decisionRef;retirementManifest=$manifestRef};owner="executor-doctor-wrapper";verifier="independent-verifier-required";observationExpiry=$expiry;status="draft";authorityBoundary="template_only_no_approval_or_deletion_authority"};W (Join-Path $OutDir "compatibility-retirement-ticket.json") $ticket;& $CodeIntel compatibility retirement-ticket lint --ticket (Join-Path $OutDir "compatibility-retirement-ticket.json") --evaluated-at $EvaluatedAt|Out-Null;if($LASTEXITCODE-ne0){throw "E01 lint failed"};$ticketRef=Ref "code-intel-compatibility-retirement-ticket-template.v1" "compatibility.retirement-ticket-template" "compatibility-retirement-ticket.json";$ticketDecl=($registry.integrations|Where-Object id -eq "compatibility.retirement-ticket-template").capabilityDeclaration;$e01=[ordered]@{schema="code-intel-capability-request.v1";capability="compatibility.retirement-ticket-template";contractVersion=1;implementation=$ticketDecl.implementation;snapshot=$snap;options=[ordered]@{evaluatedAt=$EvaluatedAt};inputs=@($ticketRef,$manifestRef,$decisionRef,$diffRef);effectPolicy=[ordered]@{allowedEffects=$ticketDecl.allowedEffects}};W (Join-Path $OutDir "e01-request.json") $e01;$o=@(& $CodeIntel capability exec compatibility.retirement-ticket-template --request (Join-Path $OutDir "e01-request.json") --out (Join-Path $OutDir e01-out) --artifact-root $OutDir 2>&1);$x=$LASTEXITCODE;$txt=$o-join"`n";[IO.File]::WriteAllText((Join-Path $OutDir "e01-stderr.txt"),$txt,[Text.UTF8Encoding]::new($false));if($x-ne65-or$txt-notmatch"ticket requires an approved E00 decision"){throw "E01 wrong boundary: $x $txt"}
if((Get-FileHash $checkPath -Algorithm SHA256).Hash.ToLowerInvariant()-ne$checkHash){throw "E09 changed bootstrap"};$status=[ordered]@{schema="code-intel-compatibility-retirement-execution-status.v1";retirementId=$rid;decision="blocked";liveDirectDoctorRoute=$true;publicPreflightUsesB10=$false;bootstrapRetained=$true;bootstrapNonAuthoritative=$nonAuthoritative;bootstrapRegistered=$true;bootstrapOwned=$true;bootstrapExpiring=$expiryDeclared;deletionExecuted=$false;retired=$false;blockers=@($decision.blockers|Sort-Object);gainLedgerProjection=$decision.gainLedgerProjection;boundary="B10 is available but public preflight still directly invokes the retained non-authoritative bootstrap, whose expiry is not yet declared."};W (Join-Path $OutDir "status.json") $status;$status|ConvertTo-Json -Depth 12 -Compress
