[CmdletBinding(DefaultParameterSetName="Rehearsal")]param([Parameter(Mandatory=$true,ParameterSetName="Apply")][string]$TargetPath,[Parameter(Mandatory=$true,ParameterSetName="Rehearsal")][string]$RehearsalRoot,[string]$RepoRoot=(Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),[string]$SourceRevision="working-tree-bounded-source")
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
$live=Join-Path $RepoRoot "run-code-intel.ps1";$source=[IO.File]::ReadAllText($live);$liveHash=(Get-FileHash $live -Algorithm SHA256).Hash.ToLowerInvariant()
$functions='(?s)function New-HospitalProtocol \{.*?(?=\r?\nfunction Get-CodeIntelSentruxStep)';$call='(?s)\$hospitalReport = New-CodeIntelHospitalReport .*?Convert-HospitalReportToMarkdown \$hospitalReport \| Set-Content -LiteralPath \$hospitalMarkdownPath -Encoding UTF8\r?\n'
$fm=[regex]::Match($source,$functions);$cm=[regex]::Match($source,$call);if(-not$fm.Success-or-not$cm.Success){throw "current snapshot lacks embedded Hospital branch"}
$deleted=[regex]::Replace([regex]::Replace($source,$functions,"",1),$call,"",1)
if($PSCmdlet.ParameterSetName-eq"Rehearsal"){if(Test-Path $RehearsalRoot){throw "rehearsal root must be exclusive"};New-Item -ItemType Directory $RehearsalRoot|Out-Null;$TargetPath=Join-Path $RehearsalRoot "run-code-intel.ps1";[IO.File]::WriteAllText($TargetPath,$deleted,[Text.UTF8Encoding]::new($false))}
$target=[IO.Path]::GetFullPath($TargetPath);$text=[IO.File]::ReadAllText($target);if($text-ne$deleted){throw "rollback target is not the exact bounded Hospital deletion result"}
[IO.File]::WriteAllText($target,$source,[Text.UTF8Encoding]::new($false));$targetHash=(Get-FileHash $target -Algorithm SHA256).Hash.ToLowerInvariant();if($targetHash-ne$liveHash){throw "rollback did not restore the exact current snapshot"};if((Get-FileHash $live -Algorithm SHA256).Hash.ToLowerInvariant()-ne$liveHash){throw "live facade changed"}
[ordered]@{schema="code-intel-compatibility-rollback-rehearsal.v1";branchId="run-code-intel.hospital.embedded-diagnosis-render";target=$target;sourceRevision=$SourceRevision;rehearsal=($PSCmdlet.ParameterSetName-eq"Rehearsal");changedFiles=@($target);exactRestore=$true;sourceSha256=$liveHash;targetSha256=$targetHash;replacementChanged=$false;publicationChanged=$false;indexChanged=$false;doctorChanged=$false;liveFacadeChanged=$false}|ConvertTo-Json -Compress
