[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$PacketRoot,[string]$RepoRoot=(Split-Path (Split-Path $PSScriptRoot -Parent) -Parent))
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
function J([string]$r){$p=Join-Path $PacketRoot $r;if(-not(Test-Path $p -PathType Leaf)){throw "missing $r"};Get-Content $p -Raw|ConvertFrom-Json}
function S([string]$t){([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($t)))).ToLowerInvariant()}
$t=J "compatibility-retirement-ticket.json";$m=J "compatibility-retirement-manifest.json";$d=J "compatibility-retirement-deletion-diff.json";$g=J "gate-out/compatibility-retirement-decision.json";$s=J "status.json"
$b="run-code-intel.hospital.embedded-diagnosis-render";$c="run-code-intel.ps1::$b";$r="diagnosis.hospital"
if($t.legacyBranch.branchId-ne$b-or$t.legacyBranch.callPath-ne$c-or$m.approvalSubject.legacyBranch.callPath-ne$c){throw "E08 branch/callPath mismatch"}
if(@($t.affectedFiles).Count-ne1-or$t.affectedFiles[0]-ne"run-code-intel.ps1"-or@($d.affectedFiles).Count-ne1-or$d.affectedFiles[0]-ne"run-code-intel.ps1"){throw "E08 escaped file boundary"}
if($t.replacement.capabilityId-ne$r-or$m.approvalSubject.replacement.capabilityId-ne$r){throw "E08 replacement mismatch"}
if($d.patch.algorithm-ne"replayable-delete-only-v1"-or@($d.patch.files).Count-ne1-or@($d.patch.files[0].hunks).Count-ne2){throw "E08 patch must contain exactly two replayable hunks"}
$file=$d.patch.files[0];$base=[string]$file.baseText;$result=[string]$file.resultText
if((S $base)-ne$file.baseBlobSha256-or(S $result)-ne$file.resultBlobSha256){throw "E08 blob hash mismatch"}
$canonical=@($d.patch.files);if((S (ConvertTo-Json -InputObject $canonical -Depth 30 -Compress))-ne$d.patch.sha256){throw "E08 canonical patch hash mismatch"}
$baseLines=@($base-split"`n");$replayed=for($i=1;$i-le$baseLines.Count;$i++){if(-not@($file.hunks|Where-Object{$i-ge$_.oldStart-and$i-lt($_.oldStart+$_.oldLines)}).Count){$baseLines[$i-1]}};$replayed=$replayed-join"`n";if($replayed-ne$result){throw "E08 patch replay mismatch"}
if($base-notmatch'function New-HospitalProtocol'-or$base-notmatch'\$hospitalReport = New-CodeIntelHospitalReport'-or$result-match'function New-HospitalProtocol'-or$result-match'\$hospitalReport = New-CodeIntelHospitalReport'){throw "E08 patch does not remove bounded Hospital authority"}
foreach($h in @($file.hunks)){if($h.newLines-ne0-or@($h.addedLines).Count-ne0-or$h.oldLines-le0){throw "E08 patch is not deletion-only"};$joined=@($h.deletedLines)-join"`n";if($joined-match'run-complete\.json|update-code-intel-index|doctor_adapter|run_commit|artifact_index'){throw "E08 patch touches excluded ownership"}}
$frozen=@('run-code-intel.ps1','crates/code-intel-cli/src/hospital_diagnosis.rs','orchestration/integrations.json','crates/code-intel-cli/src/run_commit.rs','crates/code-intel-cli/src/artifact_index.rs','crates/code-intel-cli/src/doctor_adapter.rs');$snapshot=S (($frozen|ForEach-Object{(Get-FileHash (Join-Path $RepoRoot $_) -Algorithm SHA256).Hash.ToLowerInvariant()})-join"`n");if($snapshot-ne$m.snapshotIdentity){throw "E08 snapshot drift"}
$e=@(Get-ChildItem (Join-Path $PacketRoot evidence) -Filter *.json -File|ForEach-Object{Get-Content $_.FullName -Raw|ConvertFrom-Json});if($e.Count-ne12){throw "E08 must have twelve evidence objects"};if(@($e|Where-Object{$_.legacyBranchId-ne$b-or$_.replacementCapabilityId-ne$r}).Count){throw "E08 evidence identity mismatch"}
$gold=$e|Where-Object evidenceClass -eq golden_parity;$contract=$e|Where-Object evidenceClass -eq contract_parity;$effects=$e|Where-Object evidenceClass -eq effect_parity;$rollback=$e|Where-Object evidenceClass -eq rollback_execution
if($gold.details.sameUntrustedAuthoritativeFixture-ne$true-or$gold.details.machineParity-ne$true-or$gold.details.executedTestCount-ne7){throw "E08 golden parity incomplete"}
if($contract.details.precedenceFailClosed-ne$true-or$contract.details.a09SeededA01Route-ne$true){throw "E08 contract parity incomplete"}
if($effects.details.machineAuthority-ne"hospital-report.json"-or$effects.details.markdownRebuildable-ne$true-or$effects.details.untrustedViewCannotChangeVerdict-ne$true){throw "E08 effect parity incomplete"}
if($rollback.details.exactRestore-ne$true-or$rollback.details.sourceSha256-ne$rollback.details.targetSha256){throw "E08 rollback is not exact"}
$required=@('unproven_compatibility_window','unproven_independent_approval','unproven_replacement_atom','unproven_usage_observation');foreach($x in $required){if(@($g.blockers)-notcontains$x){throw "E08 missing blocker $x"}}
if($g.decision-ne"blocked"-or$s.decision-ne"blocked"-or$s.deletionExecuted-ne$false-or$s.retired-ne$false-or$s.liveEmbeddedAuthority-ne$true-or$s.normalFacadeUsesB09-ne$false){throw "E08 cannot claim deletion/retirement"}
$stderr=Get-Content (Join-Path $PacketRoot "e01-stderr.txt") -Raw;if($stderr-notmatch'ticket requires an approved E00 decision'){throw "E01 rejection boundary mismatch"}
$boundary=& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "tools\compatibility\Test-HospitalRetirementBoundary.ps1")|ConvertFrom-Json;if($boundary.embeddedFunctionBlocks-ne1-or$boundary.embeddedCallBlocks-ne1-or$boundary.b09RegistryRoutes-ne1-or$boundary.normalFacadeUsesB09-ne$false-or$boundary.legacyRemainsAuthority-ne$true-or$boundary.publicationTouched-ne$false-or$boundary.indexTouched-ne$false-or$boundary.doctorTouched-ne$false){throw "live E08 boundary changed"}
[ordered]@{ok=$true;retirementId=$s.retirementId;decision=$s.decision;deletionExecuted=$s.deletionExecuted;retired=$s.retired;evidenceCount=$e.Count;legacyHunks=2;normalFacadeUsesB09=$false;liveEmbeddedAuthority=$true;excludedPathsUnchanged=$true}|ConvertTo-Json -Compress
