[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$PacketRoot,[string]$RepoRoot=(Split-Path (Split-Path $PSScriptRoot -Parent) -Parent))
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop";function J([string]$r){$p=Join-Path $PacketRoot $r;if(-not(Test-Path $p -PathType Leaf)){throw "missing $r"};Get-Content $p -Raw|ConvertFrom-Json};function S([string]$t){([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($t)))).ToLowerInvariant()}
$t=J "compatibility-retirement-ticket.json";$m=J "compatibility-retirement-manifest.json";$d=J "compatibility-retirement-deletion-diff.json";$g=J "gate-out/compatibility-retirement-decision.json";$s=J "status.json";$b="update-code-intel-index.legacy-compatibility-traversal";$c="update-code-intel-index.ps1::$b";$r="artifact.index-committed-only"
if($t.legacyBranch.branchId-ne$b-or$t.legacyBranch.callPath-ne$c-or$m.approvalSubject.legacyBranch.callPath-ne$c-or$t.replacement.capabilityId-ne$r){throw "E10 identity mismatch"};if(@($t.affectedFiles).Count-ne1-or$t.affectedFiles[0]-ne"update-code-intel-index.ps1"){throw "E10 escaped file boundary"};if($d.patch.algorithm-ne"replayable-delete-only-v1"-or@($d.patch.files).Count-ne1-or@($d.patch.files[0].hunks).Count-ne1){throw "E10 patch shape invalid"}
$f=$d.patch.files[0];if((S $f.baseText)-ne$f.baseBlobSha256-or(S $f.resultText)-ne$f.resultBlobSha256-or(S (ConvertTo-Json -InputObject @($d.patch.files)-Depth 40 -Compress))-ne$d.patch.sha256){throw "E10 patch hash invalid"};$h=$f.hunks[0];if($h.newLines-ne0-or@($h.addedLines).Count-ne0-or$h.oldLines-le0){throw "E10 patch is not deletion only"};if($f.baseText-notmatch'function Read-JsonFile'-or$f.resultText-match'function Read-JsonFile'-or$f.resultText-notmatch'"artifact", "index"'-or$f.resultText-notmatch'exit 0'){throw "E10 branch deletion or A08 preservation invalid"}
$baseLines=@($f.baseText-split"`n");$kept=@();for($i=1;$i-le$baseLines.Count;$i++){if(-not($i-ge$h.oldStart-and$i-lt($h.oldStart+$h.oldLines))){$kept+=$baseLines[$i-1]}};if(($kept-join"`n")-cne$f.resultText){throw "E10 patch replay failed"}
$e=@(Get-ChildItem (Join-Path $PacketRoot evidence) -Filter *.json -File|ForEach-Object{Get-Content $_.FullName -Raw|ConvertFrom-Json});if($e.Count-ne11-or@($e|Where-Object{$_.legacyBranchId-ne$b-or$_.replacementCapabilityId-ne$r}).Count){throw "E10 evidence mismatch"};$gold=$e|Where-Object evidenceClass -eq golden_parity;$contract=$e|Where-Object evidenceClass -eq contract_parity;$effects=$e|Where-Object evidenceClass -eq effect_parity;$rollback=$e|Where-Object evidenceClass -eq rollback_execution
if($gold.details.validOnlyAdmission-ne$true-or$gold.details.stagingRejected-ne$true-or$gold.details.markerlessRejected-ne$true-or$gold.details.forgedRejected-ne$true-or$contract.details.rebuildIncrementalByteEquivalent-ne$true-or$contract.details.dirtyStagingGuard-ne$true){throw "E10 parity incomplete"};if($effects.details.legacyOutputDiagnosticOnly-ne$true-or$effects.details.legacyCanWriteAuthoritativeIndex-ne$false){throw "legacy authority overstated"};if($rollback.details.exactReplay-ne$true-or$rollback.details.sourceSha256-ne$rollback.details.targetSha256){throw "rollback not exact"}
$rehearsal=Join-Path $RepoRoot ([string]$rollback.details.target-replace'/',[IO.Path]::DirectorySeparatorChar);if((Get-FileHash $rehearsal -Algorithm SHA256).Hash.ToLowerInvariant()-ne$rollback.details.targetSha256-or(Get-FileHash (Join-Path $RepoRoot "update-code-intel-index.ps1") -Algorithm SHA256).Hash.ToLowerInvariant()-ne$rollback.details.sourceSha256){throw "rollback drift"}
$required=@('dependency_approval_set_mismatch','unproven_compatibility_window','unproven_dependency_approval','unproven_independent_approval','unproven_usage_observation');foreach($x in $required){if(@($g.blockers)-notcontains$x){throw "missing blocker $x"}};if(@($g.blockers).Count-ne5-or$g.decision-ne"blocked"-or$s.deletionExecuted-ne$false-or$s.retired-ne$false-or$s.publicNormalUsesA08-ne$true-or$s.publicLegacyRouteReachable-ne$true-or$s.e05Decision-ne"blocked"){throw "E10 blocked state invalid"};if((Get-Content (Join-Path $PacketRoot "e01-stderr.txt")-Raw)-notmatch'ticket requires an approved E00 decision'){throw "E01 boundary invalid"}
$boundary=& pwsh -NoLogo -NoProfile -File (Join-Path $RepoRoot "tools\compatibility\Test-IndexRetirementBoundary.ps1")|ConvertFrom-Json;if($boundary.legacyTraversalBlocks-ne1-or$boundary.publicNormalUsesA08-ne$true-or$boundary.publicLegacyRouteReachable-ne$true-or$boundary.e05Decision-ne"blocked"){throw "live boundary changed"};[ordered]@{ok=$true;retirementId=$s.retirementId;decision=$s.decision;evidenceCount=$e.Count;legacyHunks=1;publicNormalUsesA08=$true;publicLegacyRouteReachable=$true;e05Decision="blocked";deletionExecuted=$false;retired=$false}|ConvertTo-Json -Compress
