//! Frozen-source digest helpers for the compatibility retirement tooling.
//!
//! Rust port of `legacy/tools/compatibility/Get-FrozenManifestProjection.ps1`.
//! See docs/decisions/README.md and AGENTS.md's "Language direction" section:
//! new orchestration/policy work belongs here, not in new `.ps1`.
//!
//! Byte-for-byte parity with the retired PowerShell implementation is
//! deliberately NOT a goal. The PowerShell generator and verifier only ever
//! had to agree with each other (both dot-source the same helper); nothing
//! outside this crate reads a frozen-set digest and compares it to a
//! PowerShell-computed value. A retirement packet generated by this Rust
//! tooling recomputes its own `snapshotIdentity` from scratch, so this port
//! only needs to be internally deterministic, not bit-compatible with the
//! script it replaces.
//!
//! An entry in a frozen set is either a repository-relative file path, or a
//! projection token `manifest-projection:<manifest path>#<integration
//! id>[,<integration id>...]`. Root resolution matches the PowerShell
//! original: `crates/` and `orchestration/` paths resolve against the
//! pipeline repository root, everything else against the PowerShell root.

use std::path::{Path, PathBuf};

use serde_json::{json, Value};

use crate::capability::sha256_hex;

pub(crate) fn resolve_frozen_source_path(
    relative: &str,
    repo_root: &Path,
    pipeline_repo_root: &Path,
) -> PathBuf {
    let root = if relative.starts_with("crates/") || relative.starts_with("orchestration/") {
        pipeline_repo_root
    } else {
        repo_root
    };
    root.join(relative)
}

/// SHA-256 over `{ schema, policy, integrations }` for exactly the named
/// integration entries, selected from `manifest_path`'s `integrations` array,
/// ordered by id with a byte-wise (ordinal) sort so the digest never depends
/// on the registry's file order. Missing or duplicated ids are a hard error:
/// an empty projection would be a silent governance hole.
pub(crate) fn manifest_projection_digest(
    manifest_path: &Path,
    integration_ids: &[String],
) -> Result<String, String> {
    if integration_ids.is_empty() {
        return Err("manifest projection requires at least one integration id".into());
    }
    let text = std::fs::read_to_string(manifest_path)
        .map_err(|e| format!("read {}: {e}", manifest_path.display()))?;
    let manifest: Value = serde_json::from_str(&text)
        .map_err(|e| format!("parse {}: {e}", manifest_path.display()))?;
    let integrations = manifest["integrations"]
        .as_array()
        .ok_or("manifest.integrations must be an array")?;
    let mut ordered = integration_ids.to_vec();
    ordered.sort();
    let mut selected = Vec::with_capacity(ordered.len());
    for id in &ordered {
        let matched: Vec<&Value> = integrations
            .iter()
            .filter(|entry| entry["id"] == Value::String(id.clone()))
            .collect();
        if matched.len() != 1 {
            return Err(format!(
                "manifest projection requires exactly one '{id}' integration in {} (found {})",
                manifest_path.display(),
                matched.len()
            ));
        }
        selected.push(matched[0].clone());
    }
    let projection = json!({
        "schema": "code-intel-frozen-manifest-projection.v1",
        "policy": manifest["policy"],
        "integrations": selected
    });
    let bytes = serde_json::to_vec(&projection)
        .map_err(|e| format!("serialize frozen manifest projection: {e}"))?;
    Ok(sha256_hex(&bytes))
}

/// SHA-256 of one frozen-set entry: a manifest-projection digest for
/// `manifest-projection:...` entries, or a plain file digest otherwise.
pub(crate) fn frozen_source_digest(
    entry: &str,
    repo_root: &Path,
    pipeline_repo_root: &Path,
) -> Result<String, String> {
    if let Some(spec) = entry.strip_prefix("manifest-projection:") {
        let mut parts = spec.splitn(2, '#');
        let manifest_relative = parts.next().unwrap_or("");
        let ids_part = parts
            .next()
            .ok_or_else(|| format!("malformed frozen projection entry: {entry}"))?;
        let ids: Vec<String> = ids_part
            .split(',')
            .map(str::trim)
            .filter(|id| !id.is_empty())
            .map(str::to_string)
            .collect();
        if manifest_relative.trim().is_empty() || ids.is_empty() {
            return Err(format!("malformed frozen projection entry: {entry}"));
        }
        let manifest_path =
            resolve_frozen_source_path(manifest_relative, repo_root, pipeline_repo_root);
        return manifest_projection_digest(&manifest_path, &ids);
    }
    let path = resolve_frozen_source_path(entry, repo_root, pipeline_repo_root);
    let bytes = std::fs::read(&path).map_err(|e| format!("read {}: {e}", path.display()))?;
    Ok(sha256_hex(&bytes))
}

/// SHA-256 of the newline-joined per-entry digests, in the given frozen-set
/// order. Both a packet's generator and its verifier must call this with the
/// identical frozen set to agree on a `snapshotIdentity`.
pub(crate) fn frozen_source_identity(
    frozen_set: &[String],
    repo_root: &Path,
    pipeline_repo_root: &Path,
) -> Result<String, String> {
    let mut digests = Vec::with_capacity(frozen_set.len());
    for entry in frozen_set {
        digests.push(frozen_source_digest(entry, repo_root, pipeline_repo_root)?);
    }
    Ok(sha256_hex(digests.join("\n").as_bytes()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn write(path: &Path, text: &str) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, text).unwrap();
    }

    #[test]
    fn crates_and_orchestration_paths_resolve_against_the_pipeline_root() {
        let repo_root = Path::new("/repo/legacy");
        let pipeline_root = Path::new("/repo");
        assert_eq!(
            resolve_frozen_source_path(
                "crates/code-intel-cli/src/main.rs",
                repo_root,
                pipeline_root
            ),
            pipeline_root.join("crates/code-intel-cli/src/main.rs")
        );
        assert_eq!(
            resolve_frozen_source_path("orchestration/integrations.json", repo_root, pipeline_root),
            pipeline_root.join("orchestration/integrations.json")
        );
        assert_eq!(
            resolve_frozen_source_path("run-code-intel.ps1", repo_root, pipeline_root),
            repo_root.join("run-code-intel.ps1")
        );
    }

    #[test]
    fn projection_digest_is_order_independent_over_requested_ids() {
        let dir = std::env::temp_dir().join(format!("fmp-test-{}", std::process::id()));
        let manifest_path = dir.join("integrations.json");
        write(
            &manifest_path,
            r#"{"policy":{"mode":"strict"},"integrations":[{"id":"b.thing","x":1},{"id":"a.thing","y":2}]}"#,
        );
        let ascending =
            manifest_projection_digest(&manifest_path, &["a.thing".into(), "b.thing".into()])
                .unwrap();
        let descending =
            manifest_projection_digest(&manifest_path, &["b.thing".into(), "a.thing".into()])
                .unwrap();
        assert_eq!(ascending, descending);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn projection_digest_changes_when_selected_integration_content_changes() {
        let dir = std::env::temp_dir().join(format!("fmp-test-{}", std::process::id() + 1));
        let manifest_path = dir.join("integrations.json");
        write(
            &manifest_path,
            r#"{"policy":{},"integrations":[{"id":"a.thing","required":false}]}"#,
        );
        let before = manifest_projection_digest(&manifest_path, &["a.thing".into()]).unwrap();
        write(
            &manifest_path,
            r#"{"policy":{},"integrations":[{"id":"a.thing","required":true}]}"#,
        );
        let after = manifest_projection_digest(&manifest_path, &["a.thing".into()]).unwrap();
        assert_ne!(before, after);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn projection_rejects_zero_or_duplicated_matches() {
        let dir = std::env::temp_dir().join(format!("fmp-test-{}", std::process::id() + 2));
        let manifest_path = dir.join("integrations.json");
        write(
            &manifest_path,
            r#"{"policy":{},"integrations":[{"id":"dup"},{"id":"dup"}]}"#,
        );
        assert!(manifest_projection_digest(&manifest_path, &["missing".into()]).is_err());
        assert!(manifest_projection_digest(&manifest_path, &["dup".into()]).is_err());
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn malformed_projection_entries_are_rejected() {
        let repo_root = Path::new("/repo/legacy");
        let pipeline_root = Path::new("/repo");
        assert!(frozen_source_digest(
            "manifest-projection:no-hash-separator",
            repo_root,
            pipeline_root
        )
        .is_err());
        assert!(
            frozen_source_digest("manifest-projection:#ids-only", repo_root, pipeline_root)
                .is_err()
        );
        assert!(
            frozen_source_digest("manifest-projection:path.json#", repo_root, pipeline_root)
                .is_err()
        );
    }

    #[test]
    fn source_identity_is_order_sensitive_over_the_frozen_set() {
        let dir = std::env::temp_dir().join(format!("fmp-test-{}", std::process::id() + 3));
        let a = dir.join("a.txt");
        let b = dir.join("b.txt");
        write(&a, "alpha");
        write(&b, "beta");
        let repo_root = dir.as_path();
        let pipeline_root = dir.as_path();
        let forward = frozen_source_identity(
            &["a.txt".to_string(), "b.txt".to_string()],
            repo_root,
            pipeline_root,
        )
        .unwrap();
        let reversed = frozen_source_identity(
            &["b.txt".to_string(), "a.txt".to_string()],
            repo_root,
            pipeline_root,
        )
        .unwrap();
        assert_ne!(forward, reversed);
        fs::remove_dir_all(&dir).ok();
    }
}
